# Generated by Django 4.1.2 on 2022-10-27 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_artiste_lyric_song_delete_school_delete_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='Song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='Artiste',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.artiste'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lyric',
            name='content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='lyric',
            name='song_id',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
